heartbeatConfig:
  heartbeat.yml: |
    heartbeat.autodiscover:
      providers:
        - type: kubernetes

    processors:
    - add_cloud_metadata:
    - add_kubernetes_metadata:
      in_cluster: true

    output.elasticsearch:
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      hosts: ["security-master:9200"]
      ssl.certificate_authorities:
        - /usr/share/heartbeat/config/certs/elastic-certificate.pem

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/heartbeat/config/certs

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
